name: LRU Cache Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Build Essentials
      run: sudo apt-get install -y build-essential

    - name: Compile Code
      run: gcc -Wall -Wextra -o Testing Testing.c Code.c

    - name: Run Tests
      run: ./Testing
